const PASSWORD_CONFIRM = "PASSWORD_CONFIRM";
const HANDLE_PASS = "HANDLE_PASS";
const SECOND_HANDLE_PASS = "SECOND_HANDLE_PASS";


export default {
  PASSWORD_CONFIRM,
  HANDLE_PASS,
  SECOND_HANDLE_PASS
};
