const ADD_MOVIE = "ADD_MOVIE";
const DELETE_MOVIE = "DELETE_MOVIE";
const RESET_MOVIE = "RESET_MOVIE";
const DELETE_LAST = "DELETE_LAST";

export default {
  ADD_MOVIE,
  DELETE_MOVIE,
  RESET_MOVIE,
  DELETE_LAST
};
